Seoul15Algo/algorithm

wonho/Main1026.java

wonho_1026_230125

---

sooyeon/Main_1138.java
sooyeon/Main_14503.java
sooyeon/Main_14719.java

solve(1138, 14503, 14719) : sooyeon_230131

---

wonho/week4/Main1107.java
wonho/week4/Main1107.md
wonho/week4/Main12100.java
wonho/week4/Main12100.md
wonho/week4/Main14890.java
wonho/week4/Main14890.md
wonho/week4/Main9663.java
wonho/week4/Main9663.md

solve(1107, 9663, 12100, 14890): wonho_230220

---

soyun/week5/Main_1655.java
soyun/week5/Main_16934.java
soyun/week5/Main_2533.java
soyun/week5/Main_9935.java

solve(1655, 2533, 9935, 16934): soyun_230228

---

wonho/week5/Main1655.java
wonho/week5/Main16934.java
wonho/week5/Main2533.java
wonho/week5/Main9935.java

solve(1655, 2533, 9935, 16934): wonho_230228

---

sooyeon/week5/Main_1655.java
sooyeon/week5/Main_16934.java
sooyeon/week5/Main_2533.java
sooyeon/week5/Main_9935.java

solve(1655, 2533, 9935, 16934): sooyeon_230228

---

soyun/week6/Main_1377.java
soyun/week6/Main_2473.java
soyun/week6/Main_2887.java
soyun/week6/heapsort/HeapSort.java
soyun/week6/heapsort/HeapSortTest.java
soyun/week6/mergesort/MergeSort.java
soyun/week6/mergesort/MergeSortTest.java
soyun/week6/quicksort/QuickSort.java
soyun/week6/quicksort/QuickSortTest.java

solve(1377, 2473, 2887): soyun_230307

---

sooyeon/week6/App.java
sooyeon/week6/HeapSort.java
sooyeon/week6/Main_1377.java
sooyeon/week6/Main_2473.java
sooyeon/week6/Main_2887.java
sooyeon/week6/MergeSort.java
sooyeon/week6/QuickSort.java

solve(1377, 2473, 2887): sooyeon_230307

---

hyeongu/week_6/HeapSort.java
hyeongu/week_6/Main_1377.java
hyeongu/week_6/Main_2473.java
hyeongu/week_6/Main_2887.java
hyeongu/week_6/MergeSort.java
hyeongu/week_6/QuickSort.java
hyeongu/week_6/main.java

solve(1377, 2473, 2887): hyeongu_230307

---

hyeongu/week_7/Main_12865.java
hyeongu/week_7/Main_1309.java
hyeongu/week_7/Main_14002.java
hyeongu/week_7/Main_9251.java

solve(1309, 9251, 12865, 14002): hyeongu_230314

---

soyun/week7/Main_12865.java
soyun/week7/Main_1309.java
soyun/week7/Main_14002.java
soyun/week7/Main_9251.java

solve(1309, 9251, 12865, 14002): soyun_230314

---

soyun/week8/Main_11505.java
soyun/week8/Main_14621.java
soyun/week8/Main_1774.java
soyun/week8/Main_2357.java

solve(1774, 2357, 11505, 14621): soyun_230321

---

rayeon/week8/Main_11505.java
rayeon/week8/Main_14621.java
rayeon/week8/Main_1774.java
rayeon/week8/Main_2357.java

solve(1774, 2357, 11505, 14621): rayeon_230321

---

sooyeon/week8/Main_11505.java
sooyeon/week8/Main_14621.java
sooyeon/week8/Main_1774.java
sooyeon/week8/Main_2357.java

solve(1774, 2357, 11505, 14621): sooyeon_230321

---

jio/week_9/PR_이모티할인행사.java
jio/week_9/PR_자물쇠와열쇠.java
jio/week_9/PR_택배배달과수거하기.java
jio/week_9/PR_표현가능한이진트리.java

solve(week9): jio_230329

---

soyun/week9/Solution_Delivery.java
soyun/week9/Solution_Emoticon.java
soyun/week9/Solution_LockAndKey.java
soyun/week9/Solution_NumberToBinaryTree.java

solve(week_9): soyun_230328

---

rayeon/week9/BinaryTree.java
rayeon/week9/DeliveryAndPickUp.java
rayeon/week9/Emoticon.java
rayeon/week9/LockAndKey.java

solve(week_9): rayeon_230328

---

sooyeon/week9/이모티콘할인행사.java
sooyeon/week9/자물쇠와열쇠.java
sooyeon/week9/택배배달과수거하기.java
sooyeon/week9/표현가능한이진트리.java

solve(week_9): sooyeon_230328

---

hyeongu/week_9/Binary_Tree.java
hyeongu/week_9/Deliveries.java
hyeongu/week_9/Emoticons.java
hyeongu/week_9/Lock&Key.java

solve(week_9): hyeongu_230327

---

rayeon/week10/Main_1208.java
rayeon/week10/Main_1509.java
rayeon/week10/Main_1918.java
rayeon/week10/Main_9466.java

solve(1208, 1509, 1918, 9466): rayeon_230405

---

soyun/week11/Main_13334.java
soyun/week11/Main_13460.java
soyun/week11/Main_2629.java
soyun/week11/Main_6087.java

solve(2629, 6087, 13334, 13460): soyun_230412

---

hyeongu/week_11/Main_13334.java
hyeongu/week_11/Main_13460.java
hyeongu/week_11/Main_2629.java
hyeongu/week_11/Main_6087.java

solve(2629, 6087, 13334, 13460): hyeongu_230412

---

jio/week12/BJ_11066.java
jio/week12/BJ_16946.java
jio/week12/BJ_19238.java
jio/week12/BJ_9527.java
jio/week_11/BJ_13334.java
jio/week_11/BJ_13460.java
jio/week_11/BJ_2629.java
jio/week_11/BJ_6087.java

solve(2629, 6087, 13334, 13460): jio_230411

---

soyun/week12/Main_11066.java
soyun/week12/Main_16946.java
soyun/week12/Main_19238.java
soyun/week12/Main_9527.java

solve(9527, 11066, 16946, 19238): soyun_230418

---

sooyeon/week12/Main_11066.java
sooyeon/week12/Main_16946.java
sooyeon/week12/Main_19238.java
sooyeon/week12/Main_9527.java

solve(9527, 11066, 16946, 19238): sooyeon_230418

---

soyun/week13/Main_16724.java
soyun/week13/Main_1949.java
soyun/week13/Main_24337.java
soyun/week13/Main_9328.java

solve(1949, 9328, 16724, 24337): soyun_230425

---

sooyeon/week13/Main_16724.java
sooyeon/week13/Main_1949.java
sooyeon/week13/Main_24337.java
sooyeon/week13/Main_9328.java

1949(우수 마을) : https://yeeeooonn.tistory.com/16
9328(열쇠) : https://yeeeooonn.tistory.com/13
16724(피리 부는 사나이) : https://yeeeooonn.tistory.com/15
24337(가희와 탑) : https://yeeeooonn.tistory.com/14

solve(1949, 9328, 16724, 24337): sooyeon_230425

---

rayeon/week13/Main_16724.java
rayeon/week13/Main_1949.java
rayeon/week13/Main_24337.java
rayeon/week13/Main_9328.java

solve(1949, 9328, 16724, 24337): rayeon_230425

---

hyeongu/week_13/Main_16724.java
hyeongu/week_13/Main_1949.java
hyeongu/week_13/Main_24337.java
hyeongu/week_13/Main_9328.java

solve(1949, 9328, 16724, 24337): hyeongu_230425

---

rayeon/week14/Main_16954.java
rayeon/week14/Main_20061.java
rayeon/week14/Main_20188.java
rayeon/week14/Main_2138.java

solve(2138, 16954, 20061, 20188): rayeon_230503

---

soyun/week14/Main_16954.java
soyun/week14/Main_20061.java
soyun/week14/Main_20188.java
soyun/week14/Main_2138.java

[2138 전구와 스위치](https://gaebalsaebalpark.tistory.com/21)
[16954 움직이는 미로 탈출](https://gaebalsaebalpark.tistory.com/20)
[20061 모노미노도미노2](https://gaebalsaebalpark.tistory.com/22)
[20188 등산 마니아](https://gaebalsaebalpark.tistory.com/23)

solve(2138, 16954, 20061, 20188): soyun_230502

---

jio/week14/BJ_16954.java
jio/week14/BJ_20061.java
jio/week14/BJ_20188.java
jio/week14/BJ_2138.java
jio/week15/BJ_15898.java
jio/week15/BJ_1943.java
jio/week15/BJ_21611.java
jio/week15/BJ_2176.java

[2138 전구와 스위치]
https://velog.io/@lio8625/%EB%B0%B1%EC%A4%80
[16954 움직이는 미로 탈출]
https://velog.io/@lio8625/%EB%B0%B1%EC%A4%80-16954-JAVA-%EC%9B%80%EC%A7%81%EC%9D%B4%EB%8A%94-%EB%AF%B8%EB%A1%9C-%ED%83%88
[20061 모노미노모미노]
https://velog.io/@lio8625/%EB%B0%B1%EC%A4%80-20061-JAVA-%EB%AA%A8%EB%85%B8%EB%AF%B8%EB%85%B8%EB%8F%84%EB%AF%B8%EB%85%B82
[20188 등산 마니아]
https://velog.io/@lio8625/%EB%B0%B1%EC%A4%80-20188-JAVA-%EB%93%B1%EC%82%B0-%EB%A7%88%EB%8B%88%EC%95%84

solve(2138, 16954, 20061, 20188): jio_230502

---

soyun/week15/Main_15898.java
soyun/week15/Main_1943.java
soyun/week15/Main_21611.java
soyun/week15/Main_2176.java

solve(1943, 2176, 15898, 21611): soyun_230510

---

wonho/week15/Q15898.java
wonho/week15/Q1943.java
wonho/week15/Q21611.java
wonho/week15/Q2176.java

solve(1943, 2176, 15898, 21611): wonho_230510

---

sooyeon/week16/Main_20210.java
sooyeon/week16/Main_20543.java
sooyeon/week16/Main_3687.java
sooyeon/week16/Main_4195.java

<ol>
<li><a href="https://yeeeooonn.tistory.com/17">3687 : 성냥개비</a></li>
<li><a href="https://yeeeooonn.tistory.com/20">4195 : 친구 네트워크</a></li>
<li><a href="https://yeeeooonn.tistory.com/18">20210 : 파일 탐색기</a></li>
<li><a href="https://yeeeooonn.tistory.com/19">20543 : 폭탄 던지는 태영이</a></li>
</ol>

solve(3687, 4195, 20210, 20543): sooyeon_230524

---

jio/week16/BJ_20210.java
jio/week16/BJ_20543.java
jio/week16/BJ_3687.java
jio/week16/BJ_4195.java

solve(3687, 4195, 20210, 20543): seojo_230524

---

soyun/week17/Main_1368.java
soyun/week17/Main_14725.java
soyun/week17/Main_3665.java

ϵ( ‘Θ’ )϶
[1368 물대기](https://gaebalsaebalpark.tistory.com/25)
[14725 개미굴](https://gaebalsaebalpark.tistory.com/24)
[3665 최종순위](https://gaebalsaebalpark.tistory.com/26)

solve(1368, 3665, 14725): soyun_230531

---

jio/week18/BJ_1368.java
jio/week18/BJ_14725.java
jio/week18/BJ_3665.java

solve(1368, 3665, 14725): jio_230531

---

rayeon/week20/Main_15732.java
rayeon/week20/Main_16947.java
rayeon/week20/Main_16985.java
rayeon/week20/Main_22856.java

solve(15732, 16947, 16985, 22856): rayeon_230614

---

sooyeon/week20/Main_15732.java
sooyeon/week20/Main_16947.java
sooyeon/week20/Main_16985.java
sooyeon/week20/Main_22856.java

solve(15732, 16947, 16985, 22856): sooyeon_230614

---

soyun/week18/Main_15732.java
soyun/week18/Main_16947.java
soyun/week18/Main_16985.java
soyun/week18/Main_22856.java

solve(15732, 16947, 16985, 22856): soyun_230613

---

jio/week20/BJ_15732.java
jio/week20/BJ_16947.java
jio/week20/BJ_16985.java
jio/week20/BJ_22856.java

[백준 22856 JAVA: 트리 순회](https://velog.io/@lio8625/%ED%8A%B8%EB%A6%AC-%EC%88%9C%ED%9A%8C)
[백준 16947 JAVA: 서울 지하철 2호선](https://velog.io/@lio8625/%EB%B0%B1%EC%A4%80-16947-JAVA-%EC%84%9C%EC%9A%B8-%EC%A7%80%ED%95%98%EC%B2%A0-2%ED%98%B8%EC%84%A0)
[백준 16985 JAVA: Maaaaaaaaaze](https://velog.io/@lio8625/%E3%85%87)
[백준 15732 JAVA: 도토리 숨기기](https://velog.io/@lio8625/%EB%B0%B1%EC%A4%80-15732-JAVA-%EB%8F%84%ED%86%A0%EB%A6%AC-%EC%88%A8%EA%B8%B0%EA%B8%B0)

solve(15732, 16947, 16985, 22856): jio_230614

---

hyeongu/week_19/Main_15732.java
hyeongu/week_19/Main_16947.java
hyeongu/week_19/Main_16985.java
hyeongu/week_19/Main_22856.java

solve(15732, 16947, 16985, 22856): hyeongu_230614

---

jio/week21/BJ_1507.java
jio/week21/BJ_1799.java
jio/week21/BJ_20442.java

solve(1507, 1799, 20442): jio_230628

---

soyun/week21/Main_1507.java
soyun/week21/Main_1799.java
soyun/week21/Main_20442.java
soyun/week21/Main_22948.java

solve(1507, 1799, 20442, 22948): soyun_230628

---

sooyeon/week22/Main_14722.java
sooyeon/week22/Main_1939.java
sooyeon/week22/Main_20440.java
sooyeon/week22/Main_21943.java

[1939 : 중량제한](https://yeeeooonn.tistory.com/21)
[21943 : 연산최대로](https://yeeeooonn.tistory.com/22)
[14722 : 우유 도시](https://yeeeooonn.tistory.com/24)
[20440 : 🎵니가 싫어 싫어 너무 싫어 싫어 오지 마 내게 찝쩍대지마🎵 - 1](https://yeeeooonn.tistory.com/23)
¯\(°_o)/¯

solve(1939, 21943, 14722, 20440): sooyeon_230712

---

jio/week22/BJ_14722.java
jio/week22/BJ_1939.java
jio/week22/BJ_20440.java
jio/week22/BJ_21943.java

solve(1939, 21943, 14722, 20440): jio_230711

---

soyun/week19/Main_14722.java
soyun/week19/Main_1939.java
soyun/week19/Main_20440.java
soyun/week19/Main_21943.java

solve(1939, 14722, 20440, 21943): soyun_230712

---

soyun/week23/Solution_k진수에서_소수_개수_구하기.java
soyun/week23/Solution_거리두기_확인하기.java
soyun/week23/Solution_두_큐_합_같게_만들기.java
soyun/week23/Solution_양궁대회.java
soyun/week23/Solution_주차_요금_계산.java

늦어서 죄송합니다...
[내 블로그](https://gaebalsaebalpark.tistory.com/)

solve(k진수에서소수개수구하기, 거리두기확인하기, 두큐합같게만들기, 양궁대회, 주차요금계산): soyun_230726

---

jio/week23/PR_k진수에서소수개수구하기.java
jio/week23/PR_거리두기확인하기.java
jio/week23/PR_두큐합같게만들기.java
jio/week23/PR_양궁대회.java
jio/week23/PR_주차요금계산.java

[프로그래머스 - k진수에서 소수 개수 구하기](https://velog.io/@lio8625/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-k%EC%A7%84%EC%88%98%EC%97%90%EC%84%9C-%EC%86%8C%EC%88%98-%EA%B0%9C%EC%88%98-%EA%B5%AC%ED%95%98%EA%B8%B0)
[프로그래머스 - 거리두기 확인하기](https://velog.io/@lio8625/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0-%ED%99%95%EC%9D%B8%ED%95%98%EA%B8%B0)
[프로그래머스 - 두 큐합 같게 만들기](https://velog.io/@lio8625/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EB%91%90-%ED%81%90%ED%95%A9-%EA%B0%99%EA%B2%8C-%EB%A7%8C%EB%93%A4%EA%B8%B0)
[프로그래머스 - 양궁대회](https://velog.io/@lio8625/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EC%96%91%EA%B6%81%EB%8C%80%ED%9A%8C)
[프로그래머스 - 주차 요금 계산](https://velog.io/@lio8625/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC …

solve(k진수에서소수개수구하기, 거리두기확인하기, 두큐합같게만들기, 양궁대회, 주차요금계산): jio_230725

---

sooyeon/week25/괄호_변환.java
sooyeon/week25/뉴스_클러스터링.java
sooyeon/week25/캐시.java

[괄호변환](https://yeeeooonn.tistory.com/25)
[캐시](https://yeeeooonn.tistory.com/26)
[뉴스클러스터링](https://yeeeooonn.tistory.com/27)

solve(괄호변환, 캐시, 뉴스클러스터링): sooyeon_230822
